### ISSUE TITLE
Build fails to configure (it also makes completely arbitrary choices)

### ISSUE THREAD

**Issue by barracuda156** [stsds/MPCR#18] opened 2024-08-23 03:38 UTC
```
--->  Building R-MPCR
xinstall: mkdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build --install-tests 
* installing *source* package ‘MPCR’ ...
** package ‘MPCR’ successfully unpacked and MD5 sums checked
** using staged installation
Darwin
------------------------------------------------------------
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR/
-----------------------------------------------------------------------
SED=/usr/bin/sed
BIBINPUTS=.:/opt/local/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bib:
R_TEXI2DVICMD=/opt/local/bin/texi2dvi
LN_S=ln -s
LDFLAGS=-Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc
DEVELOPER_DIR=/Developer
R_INCLUDE_DIR=/opt/local/Library/Frameworks/R.framework/Resources/include
R_PDFVIEWER=/usr/bin/open
R_STRIP_SHARED_LIB=strip -x
R_DEFAULT_PACKAGES=
DYLD_FALLBACK_LIBRARY_PATH=/opt/local/Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/jre/lib/server:/opt/local/Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/jre/lib/server
BSTINPUTS=.:/opt/local/Library/Frameworks/R.framework/Resources/share/texmf/bibtex/bst:
R_PRINTCMD=lpr
R_VERSION=4.4.1
TMPDIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/.tmp
CPPFLAGS=-isystem/opt/local/include/LegacySupport -I/opt/local/include
LIBRARY_PATH=/opt/local/lib
R_RD4PDF=times,inconsolata,hyper
R_PAPERSIZE=a4
SOURCE_DATE_EPOCH=1724383880
_R_SHLIB_BUILD_OBJECTS_SYMBOL_TABLES_=false
NO_PROXY=*.local,169.254/16
USER=root
CCACHE_DIR=/opt/local/var/macports/build/.ccache
COMMAND_MODE=legacy
R_PACKAGE_NAME=MPCR
R_PACKAGE_DIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build/00LOCK-MPCR/00new/MPCR
TAR=/opt/local/bin/gtar
CPATH=/opt/local/include
R_ZIPCMD=/opt/local/bin/zip
__CF_USER_TEXT_ENCODING=0x0:0:0
CXXFLAGS=-pipe -Os -arch ppc
COLUMNS=80
PAGER=/opt/local/bin/less
R_GZIPCMD=/opt/local/bin/gzip
PATH=/opt/local/bin:/opt/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin
FCFLAGS=-pipe -Os -m32
LC_COLLATE=C
CC_PRINT_OPTIONS=YES
PWD=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR
R_LIBS=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build/00LOCK-MPCR/00new:/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build
R_SHARE_DIR=/opt/local/Library/Frameworks/R.framework/Resources/share
EDITOR=vi
LANG=en_US.UTF-8
R_LIBS_SITE=/opt/local/Library/Frameworks/R.framework/Resources/site-library
CC_PRINT_OPTIONS_FILE=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/.CC_PRINT_OPTIONS
R_LIBRARY_DIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build
R_OSTYPE=unix
LINES=24
R_CMD=/opt/local/Library/Frameworks/R.framework/Resources/bin/Rcmd
R_BROWSER=/usr/bin/open
CXX=/opt/local/bin/g++-mp-13 -std=gnu++17
TEXINPUTS=.:/opt/local/Library/Frameworks/R.framework/Resources/share/texmf/tex/latex:
R_ARCH=
HOME=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/.home
SHLVL=4
MAKE=make
R_PAPERSIZE_USER=a4
CFLAGS=-pipe -Os -arch ppc
DYLD_LIBRARY_PATH=/opt/local/lib/libgcc:/opt/local/lib/libgcc
FC=/opt/local/bin/gfortran-mp-13
R_STRIP_STATIC_LIB=strip -S
MACOSX_DEPLOYMENT_TARGET=10.6
R_UNZIPCMD=/opt/local/bin/unzip
R_INSTALL_PKG=MPCR
R_BZIPCMD=/opt/local/bin/bzip2
R_HOME=/opt/local/Library/Frameworks/R.framework/Resources
DISPLAY=/tmp/launch-8p6TYc/org.macports:0
CC=/opt/local/bin/gcc-mp-13
R_PLATFORM=powerpc-apple-darwin10.0.0d2
R_DOC_DIR=/opt/local/Library/Frameworks/R.framework/Resources/doc
R_LIBS_USER=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/.home/Library/R/Power Macintosh/4.4/library
R_SESSION_TMPDIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/.tmp/RtmpR2T9si
_=/usr/bin/env
-----------------------------------------------------------------------
/opt/local/bin/cmake
CMake is installed in: /opt/local/bin
C Compiler used for R :  /opt/local/bin/gcc-mp-13
-- --------------- Using GCC Compiler ------------- - [Version 13.3.0]
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/local/bin/gcc-mp-13 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/local/bin/g++-mp-13 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- WORKING ON RELEASE MODE
Inside check directories
MPCR Install Result : FALSE
Finding OpenMP header using brew prefix ....
Finding OpenMP lib using brew prefix ....
OpenMP Lib Path : omp_lib-NOTFOUND
OpenMP Headers Path : omp_h-NOTFOUND
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND) (found version "4.5")
R Include Path :  /opt/local/Library/Frameworks/R.framework/Resources/include
Rcpp Lib Path :  /opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp
R Home Path :  /opt/local/Library/Frameworks/R.framework/Resources
-- Found R: /opt/local/Library/Frameworks/R.framework/Resources/include;/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/Rcpp/include  
-- Using R technology
CMake Warning (dev) at CMakeLists.txt:75 (set):
  implicitly converting 'none' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.


---------------------------------------- BLAS++
-- Checking for BLAS++

---------------------------------------- BLAS
-- Checking for BLAS
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
   Found BLAS: /opt/local/lib/libopenblas.dylib
-- BLAS done
-- Fetching BLAS++ v2023.06.00 from https://github.com/icl-utk-edu/blaspp
-- Using CMAKE_INSTALL_PREFIX = /usr/local

-- No CUDA support: gpu_backend = 

-- No HIP/ROCm support: gpu_backend = 

-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND) (found version "4.5")
-- blaspp_id = 34a24d1

-- Looking for BLAS libraries and options (blas = auto)
$BLAS_LIBRARIES
   libs:  /opt/local/lib/libopenblas.dylib
   -DBLAS_FORTRAN_ADD_                              no (library not found)
   Found BLAS library: /opt/local/lib/libopenblas.dylib

-- Checking BLAS library version
-- Checking BLAS complex return type
CMake Error at bin/_deps/blaspp-src/cmake/BLASConfig.cmake:234 (message):
  Error - Cannot detect zdotc return value.  Please check the BLAS
  installation.
Call Stack (most recent call first):
  bin/_deps/blaspp-src/CMakeLists.txt:372 (include)


-- Configuring incomplete, errors occurred!
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `all'.  Stop.
cp: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR//bin/src/libmpcr.dylib: No such file or directory
Failed: libmpcr.dylib -> src
** libs
make: Nothing to be done for `all'.
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘MPCR’ in library.dynam(lib, package, package.lib):
 shared object ‘MPCR.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build/MPCR’
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/build --install-tests 
Exit code: 1
```

P. S.
I have `blaspp` installed locally, that should have been detected.
Prefix is picked arbitrarily, on macOS it is not normal to install random stuff into a system prefix `/usr`.
OpenMP is available with gcc, it does not need any specific include directories, it is a default part of the compiler itself.

**Comment by david-helmy** [comment] 2024-10-03 14:18
Hello @barracuda156,

Could you kindly provide more details regarding the branch you used and the architecture of your MacBook, so we can accurately reproduce the issue?

### To address your questions:

- **BLAS++**: The package automatically downloads and builds BLAS++ and LAPACK++ regardless of whether they are already installed. This is necessary due to specific configurations required for static linking with MPCR.
  
- **Prefix**: The default installation prefix is set to `/usr`, but it is not actively used within the code. Therefore, nothing will be installed to this path at any point during the installation process.
  
- **OpenMP**: The default versions of Clang and GCC, installed via Xcode's command-line tools, do not support OpenMP. You will need to install it manually using Homebrew, either by installing OpenMP separately or using Homebrew's version of GCC.  In your case, I see that `OpenMP_C` is detected, but `OpenMP_CXX` is not, so make sure that OpenMP is installed correctly and i will also add an extra check for OpenMP support, and you can expect that to be integrated by the start of next week.

**Closed** 2024-10-14 12:53 UTC

**Comment by david-helmy** [comment] 2024-10-14 12:54
The package is passing on all macOS systems, both on CRAN and in-house

**Comment by barracuda156** [comment] 2024-10-14 12:56
@david-helmy Sorry, I am away from my testing hardware for a few weeks, so I cannot run the build on the system which I was testing on. I return to this in about two weeks, once I am back.

**Comment by david-helmy** [comment] 2024-10-14 13:02
Hello @barracuda156 , No problem once you return try it and let me know. I also added one more check for OpenMP in the latest version and tested the package using gcc on one of our machines. if you still facing a problem after checking the following, don't hesitate to reach out.

> Hello @barracuda156,
> 
> Could you kindly provide more details regarding the branch you used and the architecture of your MacBook, so we can accurately reproduce the issue?
> 
> ### To address your questions:
> * **BLAS++**: The package automatically downloads and builds BLAS++ and LAPACK++ regardless of whether they are already installed. This is necessary due to specific configurations required for static linking with MPCR.
> * **Prefix**: The default installation prefix is set to `/usr`, but it is not actively used within the code. Therefore, nothing will be installed to this path at any point during the installation process.
> * **OpenMP**: The default versions of Clang and GCC, installed via Xcode's command-line tools, do not support OpenMP. You will need to install it manually using Homebrew, either by installing OpenMP separately or using Homebrew's version of GCC.  In your case, I see that `OpenMP_C` is detected, but `OpenMP_CXX` is not, so make sure that OpenMP is installed correctly and i will also add an extra check for OpenMP support, and you can expect that to be integrated by the start of next week.

**Comment by barracuda156** [comment] 2024-12-07 00:57
@david-helmy Well, I think, at the very minimum this should not happen:
```
cp: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-MPCR/R-MPCR/work/MPCR//bin/src/libmpcr.dylib: No such file or directory
Failed: libmpcr.dylib -> src
** libs
make: Nothing to be done for `all'.
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘MPCR’ in library.dynam(lib, package, package.lib):
 shared object ‘MPCR.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
```

Once `blaspp` fails to configure, given it is required, the installation should err out and quit.

> Could you kindly provide more details regarding the branch you used and the architecture of your MacBook, so we can accurately reproduce the issue?

That will be non-trivial to reproduce it specifically on my platform, since I use PowerPC, however the issue has nothing to do with the architecture as such. `blaspp` has issues building with certain implementations of BLAS, in particular, with OpenBLAS on older versions of macOS (I discussed that with upstream, I think we did not arrive at a solution). It does build with Apple Accelerate, but this is not what gets picked by their configure by default.

So for example, my installation links to Accelerate:
```
36-148% port -v installed blaspp | grep active
  blaspp @2024.10.26_0+accelerate (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-11-02T00:49:33+0800'

36-148% otool -L /opt/local/lib/libblaspp.dylib
/opt/local/lib/libblaspp.dylib:
	/opt/local/lib/libblaspp.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libgcc/libatomic.1.dylib (compatibility version 4.0.0, current version 4.0.0)
	/opt/local/lib/libgcc/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.34.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```

Regardless of my issue, I think it will be an definite improvement for several reasons to allow using external libs (it saves compilation time and space, it is a preferred way for downstream software distribution systems like MacPorts, pkgsrc, FreshPorts, you name it, and allows to use libs where a default installation is broken, like in my case).

P. S. Since it also requires `lapackpp`, I will leave this for the time-being, since `lapackpp` itself needs a fix, and I never found time and enough motivation to do that, so it was not added to MacPorts so far. (Its upstream was not too much interested to fix it either.)
